 name: Trigger SampleRepo2

 on:
   workflow_dispatch:
   push:
     branches:
       - main
       
 jobs:
   build:
     name: Run API
     runs-on: ubuntu-latest
     
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
         
       - name: Fetching SampleRepoOne
         run: |
           echo "Fetching SampleRepoOne"
           git remote add SampleRepoOne https://github.com/angelobryan1/SampleRepoOne.git
           git fetch SampleRepoOne
       - name: Merging SampleRepoOne
         run: |
           echo "Merging SampleRepoOne"
           git merge --no-commit --allow-unrelated-histories --no-ff SampleRepoOne/main
       - name: Pushing
         run: |
           echo "Pushing excluding .github directory"
           git reset .github
           git commit -m "Merging SampleRepoOne repository"
           git push
