 name: Trigger Worrkflow in Repo A

 on:
   repository_dispatch:
     types:
       - repo-b-push-event
       
 jobs:
  build:
     runs-on: ubuntu-latest
     
     steps:
       - name: Checkout SampleRepo2
         uses: actions/checkout@v2
