 name: Push Event


 on:
   push:
     branches: 
       - main

 jobs:
   sync:
     runs-on: ubuntu-latest
   
     steps:
       - name: Checkout Repo SampleRepoOne
         uses: actions/checkout@v2
       
       - name: Trigger Workflow in Repo A
         uses: angelobryan1/SampleRepo2/.github/workflows/Repo2actions.yml@v1
