 name: Push Event


 on:
   push:
     branches: 
       - main

 jobs:
   sync:
     runs-on: ubuntu-latest
   
     steps:
       - name: Checkout Repo SampleRepoOne
         uses: actions/checkout@v2
       
       - name: Trigger Workflow in Repo A
         uses: octokit/request-action@v2.x
         with:
           route: POST /repos/angelobryan1/SampleRepo2/dispatches
           token: ${{ secrets.REPO_A_ACCESS_TOKEN }}
           event_type: repo-b-push-event
